# Generated by Django 3.0.9 on 2020-08-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField()),
            ],
            options={
                'db_table': 'receipt_concept',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('rate', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField()),
            ],
            options={
                'db_table': 'receipt_value',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceiptGenerator.Concept')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceiptGenerator.Value'),
        ),
    ]
