# Generated by Django 3.0.9 on 2020-08-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'udes_concept',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('value', models.BigIntegerField()),
                ('rate', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'udes_price',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='ReceiptGenerator.Concept')),
            ],
            options={
                'db_table': 'udes_receipt',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReceiptGenerator.Price'),
        ),
    ]
